services:
  - type: web
    name: attio-mcp-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      # Note: ATTIO_API_KEY is now passed by Poke client for security
