services:
  - type: web
    name: poke-attio-mcp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: ATTIO_API_KEY
        sync: false  # Must be set manually in Render dashboard
